---

name: 'Generate static website'
description: 'Hosts apache server for on pull requests, which is then snapshotted'
author: Luke Mondy <luke.mondy@data61.csiro.au>

inputs:
  config:
    description: 'Path to place website content'
    required: false
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'gen static website'

runs: 
  using: 'docker'
  image: 'sel4/sel4-website'
